# Generated by Django 5.0.6 on 2024-06-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_customuser_apellido_customuser_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('proveedor', models.CharField(max_length=200)),
                ('stock', models.PositiveIntegerField()),
                ('disponibilidad_venta', models.IntegerField(choices=[(1, 'Presencial'), (2, 'Online'), (3, 'Ambas')])),
                ('disponibilidad_despacho', models.IntegerField(choices=[(1, 'Sí'), (2, 'No')])),
            ],
        ),
    ]
